name: theartofeducation.github.io - Deploy to GitHub Pages
on:
  push:
    branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
            node-version: "12.x"

      - name: Install Dependencies
        run: yarn install

      - name: Build Site
        run: yarn clean && yarn build

      - name: Deploy app 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
