name: theartofeducation.github.io
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
            node-version: "12.x"

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint
        env:
          NODE_ENV: test
